---
- hosts: web
  serial: 3
  pre_tasks:

      - name: Gathering ec2 facts
        action: ec2_facts

      - name: Instance de-register
        local_action:
            module: ec2_elb
            instance_id: "{{ ansible_ec2_instance_id }}"
            state: 'absent'
  roles:

      - role_that_updates 

  post_tasks:

      - name: Instance register
        local_action:
            module: ec2_elb
            instance_id: "{{ ansible_ec2_instance_id }}"
            ec2_elbs: "{{ item }}"
            state: 'present'
        with_items: ec2_elbs
